/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

const documents = {
    "\n  query GetRouteByPath($path: String!) {\n    routeByPath(path: $path) {\n      path\n      page {\n        id\n        type\n        locale\n        pageContent {\n          pageType\n          published\n          id\n          title\n          fullWidthLayout\n          secondaryBackground\n          createdAt\n          author {\n            id\n            name\n          }\n          metaTags {\n            key\n            value\n            type\n          }\n          sections {\n            type\n            settings {\n              key\n              value\n            }\n            blocks {\n              name\n              options {\n                width\n              }\n              components {\n                label\n                html {\n                  raw\n                  html\n                }\n                alignment\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.GetRouteByPathDocument,
};

export function graphql(source: "\n  query GetRouteByPath($path: String!) {\n    routeByPath(path: $path) {\n      path\n      page {\n        id\n        type\n        locale\n        pageContent {\n          pageType\n          published\n          id\n          title\n          fullWidthLayout\n          secondaryBackground\n          createdAt\n          author {\n            id\n            name\n          }\n          metaTags {\n            key\n            value\n            type\n          }\n          sections {\n            type\n            settings {\n              key\n              value\n            }\n            blocks {\n              name\n              options {\n                width\n              }\n              components {\n                label\n                html {\n                  raw\n                  html\n                }\n                alignment\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetRouteByPath($path: String!) {\n    routeByPath(path: $path) {\n      path\n      page {\n        id\n        type\n        locale\n        pageContent {\n          pageType\n          published\n          id\n          title\n          fullWidthLayout\n          secondaryBackground\n          createdAt\n          author {\n            id\n            name\n          }\n          metaTags {\n            key\n            value\n            type\n          }\n          sections {\n            type\n            settings {\n              key\n              value\n            }\n            blocks {\n              name\n              options {\n                width\n              }\n              components {\n                label\n                html {\n                  raw\n                  html\n                }\n                alignment\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"];

export function graphql(source: string): unknown;
export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;